const schoolUrls = {
    "West Bay Elementary": 'https://www.compareschoolrankings.org/school/bc/elementary/4545075',
    "Collingwood at Glenmore":'https://www.compareschoolrankings.org/school/bc/elementary/4596367',
    "Mulrave":"https://www.compareschoolrankings.org/school/bc/elementary/4596701",
    "Irwin Park Elementary":"https://www.compareschoolrankings.org/school/bc/elementary/4545060",
    "Ecole Pauline Johnson Elementary": "https://www.compareschoolrankings.org/school/bc/elementary/4545065",
    "Ridgeview Elementary": "https://www.compareschoolrankings.org/school/bc/elementary/4545070",
    "Chartwell Elementary":"https://www.compareschoolrankings.org/school/bc/elementary/4545030",
    "Westcot":"https://www.compareschoolrankings.org/school/bc/elementary/4545080",
    "Ecole Cedardale":"https://www.compareschoolrankings.org/school/bc/elementary/4545025",
    "St Anthonys":"https://www.compareschoolrankings.org/school/bc/elementary/4596076",
    "St Augustine":"https://www.compareschoolrankings.org/school/bc/elementary/3996138",
    "St John's":"https://www.compareschoolrankings.org/school/bc/elementary/3996435",
    "Madrona":"https://www.compareschoolrankings.org/school/bc/elementary/3996594",
    "Lord Tennyson Elementary":"https://www.compareschoolrankings.org/school/bc/elementary/3939047",
    "Shaughnessy Elementary":"https://www.compareschoolrankings.org/school/bc/elementary/3939072",
    "York House":"https://www.compareschoolrankings.org/school/bc/elementary/3996011",
    "Emily Carr":"https://www.compareschoolrankings.org/school/bc/elementary/3939044",
    "Vancouver Talmud Torah":"https://www.compareschoolrankings.org/school/bc/elementary/3996083",
    "Blessed Sacrament Schhol":"https://www.compareschoolrankings.org/school/bc/elementary/3996070",
    "Edith Cavill":"https://www.compareschoolrankings.org/school/bc/elementary/3939071",
    "Rose des Vents":"https://www.compareschoolrankings.org/school/bc/elementary/9339092",
    "Vancouver College":"https://www.compareschoolrankings.org/school/bc/elementary/3996007",
    "Dr. Annie B Jamison":"https://www.compareschoolrankings.org/school/bc/elementary/3939104",
    "Sir Wm Van Horne":"https://www.compareschoolrankings.org/school/bc/elementary/3939058",
    "Sir Wilfrid Laurier":"https://www.compareschoolrankings.org/school/bc/elementary/3939085",
    "Sir William Osler":"https://www.compareschoolrankings.org/school/bc/elementary/3939086",
    "St. Anthony of Padua":"https://www.compareschoolrankings.org/school/bc/elementary/3996662",
    "Dr R E McKechnie":"https://www.compareschoolrankings.org/school/bc/elementary/3939097",
    "Maple Grove Elementary":"https://www.compareschoolrankings.org/school/bc/elementary/3939074",
    "Quilchena Elementary":"https://www.compareschoolrankings.org/school/bc/elementary/3939075",
    "Kerrisdale Eleementary":"https://www.compareschoolrankings.org/school/bc/elementary/3939038",
    "Crofton House":"https://www.compareschoolrankings.org/school/bc/elementary/3996004",
    "Trafalgar Elementary":"https://www.compareschoolrankings.org/school/bc/elementary/3939084",
    "Southlands Elementary":"https://www.compareschoolrankings.org/school/bc/elementary/3939087",
    "St. George's":"https://www.compareschoolrankings.org/school/bc/elementary/3996002",
    "Immaculate Conception School":"https://www.compareschoolrankings.org/school/bc/elementary/3996129",
    "Lord Kitchener Elementary":"https://www.compareschoolrankings.org/school/bc/elementary/3939070",
    "Carnarvon Community School":"https://www.compareschoolrankings.org/school/bc/elementary/3939094",
    "General Gordon Elementary":"https://www.compareschoolrankings.org/school/bc/elementary/3939052",
    "Queen Elizabeth Elemetary":"https://www.compareschoolrankings.org/school/bc/elementary/3939080",
    "Ecole Jules Quesnel Elementary":"https://www.compareschoolrankings.org/school/bc/elementary/3939132",
    "Queen Mary Elementary":"https://www.compareschoolrankings.org/school/bc/elementary/3939041",
    "Our Lady of Perpetual Help":"https://www.compareschoolrankings.org/school/bc/elementary/3996173",
    "West Point Grey Academy":"https://www.compareschoolrankings.org/school/bc/elementary/3996645"
  }

  module.exports = schoolUrls;